site_name: DevOps CookBook
repo_url: https://github.com/Alpacked/devops-book
edit_uri: ./edit/main
site_description: A Collection of Useful Tools for DevOps and more

theme:
  name: material
  # favicon: web/img/favicon.ico
  features:
    - navigation.indexes

extra_css:
  - static/style.css

# The structure of the website.
# You must to update this config each time you are adding a new page.
nav:
  - ğŸ‘‹ Getting Started: getting-started.md
  - ğŸ¹ CLI:
    - ğŸ˜ ZSH:
      - zsh: cli/zsh.md
      - oh-my-zsh: cli/oh-my-zsh.md
      - powerlevel10k: cli/powerlevel10k.md
      - plugins: cli/oh-my-zsh-plugins.md
    - ğŸšª AWS SSO:
      - aws-sso: cli/aws-sso.md
      - sso-restore: cli/sso-restore.md
    - â™»ï¸ Other:
      - regctl: cli/regctl.md
      - tldr: cli/tldr.md
      - homebrew: cli/homebrew.md
      - fig: cli/fig.md
      - tmux: cli/tmux.md
      - fzf: cli/fzf.md
      - pbcopy: cli/pbcopy.md
  - ğŸ“œ Terraform:
      - tfswitch: terraform/tfswitch.md
      - terraform-docs: terraform/terraform-docs.md
  - ğŸ‘‘ Kubernetes:
      - kubectl: kubernetes/kubectl.md
      - kubens: kubernetes/kubens.md
      - kubectx: kubernetes/kubectx.md
      - helm-diff: kubernetes/helm-diff.md
      - kube-capasity: kubernetes/kube-capasity.md
  - ğŸ“š Applications:
      - vscode: applications/vscode.md
      - lens: applications/lens.md
      - sublime: applications/sublime.md
      - notion: applications/notion.md
      - colima: applications/colima.md
      - flameshot: applications/flameshot.md
      - ğŸ¤‘ For Mac:
        - cleanshot: applications/cleanshot.md

markdown_extensions:
  # Task lists support
  # https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  # https://www.mkdocs.org/user-guide/configuration/#search
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search-plugin
  - search
